### ISSUE TITLE
引用文献时怎么使用水平引用呢？

### ISSUE THREAD

**Issue by Esamin2000** [swjtuhub/SWJTU_Thesis_Template#1]
有时候引用文献时需要类似[1-12]这种水平引用，应该如何实现呢？也就是上标和水平引用的混合使用。

**Comment by xiaodl813** [comment]
请问可以详细描述一下您的问题吗？我没有理解“水平引用”指代的是什么意思。如果您可以附上截图的话最好了，谢谢。

**Comment by Esamin2000** [comment]
https://blog.csdn.net/weixin_43659721/article/details/112851272?spm=1001.2101.3001.6650.2&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-112851272-blog-120882257.235%5Ev27%5Epc_relevant_multi_platform_whitelistv3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-2-112851272-blog-120882257.235%5Ev27%5Epc_relevant_multi_platform_whitelistv3&utm_relevant_index=5

就是这种，参考文献引用上标和非上标的混合使用。

**Comment by Esamin2000** [comment]
> 请问可以详细描述一下您的问题吗？我没有理解“水平引用”指代的是什么意思。如果您可以附上截图的话最好了，谢谢。

我在网上查询了一些教程，但是因为我初学Latex，对您提供的具体的模板不知如何修改。

**Comment by xiaodl813** [comment]
> > 请问可以详细描述一下您的问题吗？我没有理解“水平引用”指代的是什么意思。如果您可以附上截图的话最好了，谢谢。
> 
> 我在网上查询了一些教程，但是因为我初学Latex，对您提供的具体的模板不知如何修改。

你可以尝试直接用 `\cite{}` 和 `\parencite{}` 两个命令试一下。修改模板应该是在 `configuration` 文件夹下，不过我手头的电脑目前没有配置 LaTeX 环境，所以具体测试可能要等到下周。

**Comment by Esamin2000** [comment]
> > > 请问可以详细描述一下您的问题吗？我没有理解“水平引用”指代的是什么意思。如果您可以附上截图的话最好了，谢谢。
> > 
> > 
> > 我在网上查询了一些教程，但是因为我初学Latex，对您提供的具体的模板不知如何修改。
> 
> 你可以尝试直接用 `\cite{}` 和 `\parencite{}` 两个命令试一下。修改模板应该是在 `configuration` 文件夹下，不过我手头的电脑目前没有配置 LaTeX 环境，所以具体测试可能要等到下周。

好的，我再尝试一下

**Comment by Esamin2000** [comment]
> > > > 请问可以详细描述一下您的问题吗？我没有理解“水平引用”指代的是什么意思。如果您可以附上截图的话最好了，谢谢。
> > > 
> > > 
> > > 我在网上查询了一些教程，但是因为我初学Latex，对您提供的具体的模板不知如何修改。
> > 
> > 
> > 你可以尝试直接用 `\cite{}` 和 `\parencite{}` 两个命令试一下。修改模板应该是在 `configuration` 文件夹下，不过我手头的电脑目前没有配置 LaTeX 环境，所以具体测试可能要等到下周。
> 
> 好的，我再尝试一下

确实是可以的，谢谢您的解答
