### ISSUE TITLE
Word 文档提交问题

### ISSUE THREAD

**Issue by Wei-Qi** [swjtuhub/SWJTU_Thesis_Template#3]
过往有要求过提交word版本的毕业论文么？

**Comment by xiaodl813** [comment]
> 过往有要求过提交word版本的毕业论文么？

有的，我们（2018级）毕业的时候教务网系统就要求提供word版本以用于查重。当时我的解决办法是跟教务处说明我是使用LaTeX排版的，但是可以提供一份pandoc自动转换的word文档以供查重。pandoc转换的word文档仅仅能转化正文，表格、公式等都是乱码。

当然，另一个办法就是通过“钞能力”上淘宝找人工转换成word文档，大概需要900元。如果你有足够的闲钱也可以搞一个完整的word传上去。

**Comment by Wei-Qi** [comment]
thanks for your information ^-^
