### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by Hanserwei** [swjtuhub/SWJTU_Thesis_Template#7]
请问每年的毕业论文的格式会有改变吗？

**Comment by xiaodl813** [comment]
可能会有格式上的微调，以教务处最新模板为准，这个模板是我22年毕业的时候搞得，是当时的最新模板。
不过说实话我觉得如果不是没事儿闲的给教务处发邮件说模板不对他们一般也懒得改模板……

**Comment by Hanserwei** [comment]
> 可能会有格式上的微调，以教务处最新模板为准，这个模板是我22年毕业的时候搞得，是当时的最新模板。
> 
> 不过说实话我觉得如果不是没事儿闲的给教务处发邮件说模板不对他们一般也懒得改模板……

问个问题，为什么我的文献引用编译不出来，我用的tex studio，编译设置了使用biber，文献引用那里选的biblatex，可还是不行，

**Comment by mobyw** [comment]
> 问个问题，为什么我的文献引用编译不出来，我用的tex studio，编译设置了使用biber，文献引用那里选的biblatex，可还是不行，

XeLaTeX -> Biber -> XeLaTeX * 2

**Comment by Hanserwei** [comment]
> > 问个问题，为什么我的文献引用编译不出来，我用的tex studio，编译设置了使用biber，文献引用那里选的biblatex，可还是不行，
> 
> 
> 
> XeLaTeX -> Biber -> XeLaTeX * 2

谢谢，没有仔细看readme.md，再次感谢
